// This file is generated by npm run build:icons
 
	type IconName =
	| "arrow-down"
	| "arrow-right"
	| "avatar"
	| "chevron-down"
	| "close"
	| "cross"
	| "dash"
	| "dots-h"
	| "dots-v"
	| "exit"
	| "folder"
	| "info"
	| "pencil"
	| "plus-circled"
	| "reader"
	| "search"
	| "transform"
	| "trash"
	| "update";
