import { cva } from 'class-variance-authority';

export const buttonVariants = cva(
	[
		'inline-flex',
		'items-center',
		'rounded-lg',
		'justify-center',
		'disabled:opacity-50',
		'disabled:pointer-events-none',
		'outline-none',
		'transition',
		'ease-in-out',
		'duration-300',
	],
	{
		variants: {
			variant: {
				primary: [
					'text-white',
					'bg-purple-400',
					'hover:bg-purple-500',
					'focus:ring-1',
					'focus:ring-purple-700',
					'active:ring-0',
					'active:bg-purple-800',
					'disabled:bg-purple-300',
					'disabled:text-white',
				],
				secondary: [
					'ring-2',
					'ring-purple-400',
					'text-gray-700',
					'hover:text-gray-900',
					'hover:ring-purple-700',
					'focus:text-gray-900',
					'focus:ring-purple-700',
					'active:text-purple-900',
					'active:ring-purple-900',
					'disabled:text-gray-400',
					'disabled:ring-purple-300',
				],
				link: [
					'text-gray-500',
					'decoration-gray-500',
					'bg-transparent',
					'hover:text-gray-600',
					'hover:decoration-gray-600',
					'hover:underline',
					'hover:bg-transparent',
					'focus:text-gray-700',
					'focus:ring-1',
					'focus:ring-purple-500',
					'focus:no-underline',
					'active:text-white',
					'active:no-underline',
					'active:ring-0',
					'active:decoration-purple-500',
					'active:text-purple-500',
					'disabled:text-gray-300',
				],
			},
			size: {
				xs: 'py-xxs px-xs text-button-xs h-[1.75rem] max-h-[1.75rem]',
				sm: 'py-xs px-md text-button-sm h-[2.25rem] max-h-[2.25rem]',
				md: 'py-sm px-lg text-button-md h-[2.625rem] max-h-[2.625rem]',
				lg: 'py-sm px-lg text-button-lg h-[3rem] max-h-[3rem]',
			},
		},
		defaultVariants: {
			variant: 'primary',
			size: 'md',
		},
	},
);
